# Generated by Django 6.0.4 on 2026-04-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
